#!/usr/bin/env node
// Merge all squad_parts/*.json files into src/data/squads.js
// Run: node scripts/merge_squads.js

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const partsDir = join(__dirname, "../src/data/squad_parts");
const outFile = join(__dirname, "../src/data/squads.js");

// Canonical club name normalization — maps agent variants to real-seasons.js names
const CLUB_ALIASES = {
  // Athletic
  "Athletic Club": "Athletic Bilbao",
  "Athletic Club de Bilbao": "Athletic Bilbao",
  // Alavés
  "Deportivo Alavés": "Alavés",
  "Deportivo Álaves": "Alavés",
  // Albacete
  "Albacete Balompié": "Albacete",
  // Almería
  "UD Almería": "Almería",
  "Almería UD": "Almería",
  // Celta
  "Celta de Vigo": "Celta Vigo",
  "RC Celta": "Celta Vigo",
  "RC Celta de Vigo": "Celta Vigo",
  // Compostela
  "SD Compostela": "Compostela",
  // Getafe
  "Getafe CF": "Getafe",
  // Mallorca
  "RCD Mallorca": "Mallorca",
  // Villarreal
  "Villarreal CF": "Villarreal",
  // Osasuna
  "CA Osasuna": "Osasuna",
  "Club Atlético Osasuna": "Osasuna",
  // Racing
  "Racing de Santander": "Racing Santander",
  "Racing Club de Santander": "Racing Santander",
  // Tenerife
  "CD Tenerife": "Tenerife",
  "Club Deportivo Tenerife": "Tenerife",
  // Sporting
  "Sporting de Gijón": "Sporting Gijón",
  "Real Sporting de Gijón": "Sporting Gijón",
  // Málaga
  "Málaga CF": "Málaga",
  // Misc
  "Real Burgos CF": "Real Burgos",
  "Hércules CF": "Hércules",
  "UD Las Palmas": "Las Palmas",
  "Recreativo de Huelva": "Recreativo Huelva",
  "Recreativo": "Recreativo Huelva",
  "UD Salamanca": "Salamanca",
  "Xerez CD": "Xerez",
  "Rayo Vallecano de Madrid": "Rayo Vallecano",
  "Rayo": "Rayo Vallecano",
  "CD Logroñés": "CD Logroñés",  // already correct, just documenting
  "Deportivo de La Coruña": "Deportivo La Coruña",
  "Deportivo": "Deportivo La Coruña",
  "Español": "Espanyol",
  "RCD Espanyol": "Espanyol",
  "Murcia CF": "Murcia",
  "Real Murcia": "Murcia",
};

function normalizeKey(key) {
  const [club, year] = key.split("|");
  const canonical = CLUB_ALIASES[club] || club;
  if (canonical !== club) console.log(`  Normalized: "${club}" → "${canonical}"`);
  return `${canonical}|${year}`;
}

// Read and merge all JSON files
const merged = {};
const files = readdirSync(partsDir).filter(f => f.endsWith(".json")).sort();

let totalSquads = 0;
let totalPlayers = 0;

for (const file of files) {
  const raw = JSON.parse(readFileSync(join(partsDir, file), "utf8"));
  for (const [rawKey, players] of Object.entries(raw)) {
    const key = normalizeKey(rawKey);
    if (merged[key]) {
      console.warn(`  DUPLICATE key "${key}" in ${file} — overwriting`);
    }
    merged[key] = players;
    totalSquads++;
    totalPlayers += players.length;
  }
  console.log(`  Loaded ${file}: ${Object.keys(raw).length} squads`);
}

// Sort keys by club then year
const sortedKeys = Object.keys(merged).sort((a, b) => {
  const [clubA, yearA] = a.split("|");
  const [clubB, yearB] = b.split("|");
  if (clubA !== clubB) return clubA.localeCompare(clubB);
  return Number(yearA) - Number(yearB);
});

// Generate squads.js content
const lines = [
  `// AUTO-GENERATED by scripts/merge_squads.js — do not edit by hand.`,
  `// ${totalSquads} squad-seasons · ${totalPlayers} player entries`,
  `// Keyed "CLUB|YEAR" (year = season start, e.g. 1994 = 1994–95).`,
  `// media = Math.round((vel+res+agr+cal)/4) — computed at load time.`,
  ``,
  `// Stretch raw design values: elite → 94–99, weak squad → 35–55.`,
  `function s(v) { return Math.min(99, Math.max(25, Math.round(62 + (v - 62) * 1.8))); }`,
  ``,
  `function p(name, pos, age, vel, res, agr, cal) {`,
  `  const v = s(vel), r = s(res), a = s(agr), c = s(cal);`,
  `  return {`,
  `    name, pos, age,`,
  `    velocidad: v, resistencia: r, agresividad: a, calidad: c,`,
  `    media: Math.round((v + r + a + c) / 4),`,
  `  };`,
  `}`,
  ``,
  `export const SQUADS = {`,
];

for (const key of sortedKeys) {
  const players = merged[key];
  const [club, year] = key.split("|");
  lines.push(`  // ${club} ${year}–${String((Number(year) + 1) % 100).padStart(2, "0")}`);
  lines.push(`  ${JSON.stringify(key)}: [`);
  for (const pl of players) {
    const { name, pos, age, velocidad: vel, resistencia: res, agresividad: agr, calidad: cal } = pl;
    lines.push(`    p(${JSON.stringify(name)}, ${JSON.stringify(pos)}, ${age}, ${vel}, ${res}, ${agr}, ${cal}),`);
  }
  lines.push(`  ],`);
}

lines.push(`};`);
lines.push(``);

writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`\nWrote ${outFile}`);
console.log(`  ${totalSquads} squad-seasons, ${totalPlayers} players`);
console.log(`  ${sortedKeys.length} unique keys`);
